version: '2'
services:
  db:
    image: postgres:9.4.1
    ports:
      - "5432:5432"
    env_file:
      - '.env.db'

  web:
    build: .
    command: ./script/start # installs gems and starts server
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/login
    volumes_from:
      - gembox

  gembox:
    image: busybox
    volumes:
      - /gembox
