# PostgreSQL. Versions 8.2 and up are supported.

postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: 5

local: &local
  <<: *postgres
  host: <%= (ENV['LOGIN_DB_HOST'] || "localhost") %>
  username: <%= (ENV['LOGIN_DB_USER'] || "login") %>
  password: <%= (ENV['LOGIN_DB_PASSWORD'] || "") %>

remote: &remote
  <<: *local
  port: <%= ENV['LOGIN_DB_PORT'] %>
  host: <%= ENV['LOGIN_DB_HOST'] %>
  database: <%= ENV['LOGIN_DB_DATABASE'] %>

development:
  <<: *local
  port: <%= (ENV['LOGIN_DB_PORT'] || "") %>
  database: <%= (ENV['LOGIN_DB_DATABASE'] || "login_development") %>

test: &test
  <<: *local
  database: login_test

staging:
  <<: *remote

production:
  <<: *remote

cucumber:
  <<: *test
